package cr.ac.una.prograiv.gamestar.domain;
// Generated Jan 20, 2018 8:55:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Catalogos generated by hbm2java
 */
public class Catalogos  implements java.io.Serializable {


     private Integer CId;
     private Categorias categorias;
     private Detalles detalles;
     private String CNombre;
     private Date CFechaLanzamiento;
     private String CPlataforma;
     private Integer CCantidad;
     private Integer CJugadores;
     private Float CPrecAlqu;
     private Float CPrecComp;
     private String CUrlImg;
     private String CDescrip;
     private String CDesarrollador;
     private String CDistribuidor;

    public Catalogos() {
    }

    public Catalogos(Categorias categorias, Detalles detalles, String CNombre, Date CFechaLanzamiento, String CPlataforma, Integer CCantidad, Integer CJugadores, Float CPrecAlqu, Float CPrecComp, String CUrlImg, String CDescrip, String CDesarrollador, String CDistribuidor) {
       this.categorias = categorias;
       this.detalles = detalles;
       this.CNombre = CNombre;
       this.CFechaLanzamiento = CFechaLanzamiento;
       this.CPlataforma = CPlataforma;
       this.CCantidad = CCantidad;
       this.CJugadores = CJugadores;
       this.CPrecAlqu = CPrecAlqu;
       this.CPrecComp = CPrecComp;
       this.CUrlImg = CUrlImg;
       this.CDescrip = CDescrip;
       this.CDesarrollador = CDesarrollador;
       this.CDistribuidor = CDistribuidor;
    }
   
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Detalles getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Detalles detalles) {
        this.detalles = detalles;
    }
    public String getCNombre() {
        return this.CNombre;
    }
    
    public void setCNombre(String CNombre) {
        this.CNombre = CNombre;
    }
    public Date getCFechaLanzamiento() {
        return this.CFechaLanzamiento;
    }
    
    public void setCFechaLanzamiento(Date CFechaLanzamiento) {
        this.CFechaLanzamiento = CFechaLanzamiento;
    }
    public String getCPlataforma() {
        return this.CPlataforma;
    }
    
    public void setCPlataforma(String CPlataforma) {
        this.CPlataforma = CPlataforma;
    }
    public Integer getCCantidad() {
        return this.CCantidad;
    }
    
    public void setCCantidad(Integer CCantidad) {
        this.CCantidad = CCantidad;
    }
    public Integer getCJugadores() {
        return this.CJugadores;
    }
    
    public void setCJugadores(Integer CJugadores) {
        this.CJugadores = CJugadores;
    }
    public Float getCPrecAlqu() {
        return this.CPrecAlqu;
    }
    
    public void setCPrecAlqu(Float CPrecAlqu) {
        this.CPrecAlqu = CPrecAlqu;
    }
    public Float getCPrecComp() {
        return this.CPrecComp;
    }
    
    public void setCPrecComp(Float CPrecComp) {
        this.CPrecComp = CPrecComp;
    }
    public String getCUrlImg() {
        return this.CUrlImg;
    }
    
    public void setCUrlImg(String CUrlImg) {
        this.CUrlImg = CUrlImg;
    }
    public String getCDescrip() {
        return this.CDescrip;
    }
    
    public void setCDescrip(String CDescrip) {
        this.CDescrip = CDescrip;
    }
    public String getCDesarrollador() {
        return this.CDesarrollador;
    }
    
    public void setCDesarrollador(String CDesarrollador) {
        this.CDesarrollador = CDesarrollador;
    }
    public String getCDistribuidor() {
        return this.CDistribuidor;
    }
    
    public void setCDistribuidor(String CDistribuidor) {
        this.CDistribuidor = CDistribuidor;
    }




}


